version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio_s3
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234
    volumes:
      - ./minio/data:/data